# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 8, 22, 44, 16, 322895, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
